services:
  - type: web
    name: vue-music-player
    env: static
    buildCommand: cp package-minimal.json package.json && npm install && npm start
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
