services:
  - type: web
    name: vue-music-player
    env: static
    buildCommand: echo "Using pre-built dist folder - no build needed"
    staticPublishPath: ./dist
    skipInstall: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
